### ISSUE TITLE
Imported 0 messages

### ISSUE THREAD

**Issue by paveldoreuli** [pR0Ps/slack-to-discord#12]
Hi
Hello. Thanks for a very useful script. I seem to have overcome all the pitfalls, but the bot does not see messages in the channels. Although when I open and look at .json files, everything is in place. This zip exported from Slack. I don’t understand what’s wrong here (( This may be due to the fact that the channel names are not in English? Than I try to change it to English and repack again im to zip, I have error 
No such file or directory: '/var/folders/c3/jddm6hf57tx_q4vspqjhvxlr0000gn/T/tmp_eicsdb9/users.json
Thank you!
![Screenshot 2022-10-02 at 16 49 36](https://user-images.githubusercontent.com/114866573/193460233-30b4372e-63b1-4a03-a406-7777a29e143a.png)

**Comment by paveldoreuli** [comment]
I try to translit channels name, but now I have this error:
![Screenshot 2022-10-02 at 17 44 33](https://user-images.githubusercontent.com/114866573/193460194-3d70b8e9-d244-49ad-8b63-e7099013bed0.png)

**Comment by pR0Ps** [comment]
Note that your bot token is visible in the screenshots you've shared. Since anyone with that token can access your guild, you'll want to revoke it ASAP. To do this, go to https://discord.com/developers/applications/ , find your application, and in the Bot settings, click the "Reset Token" button.

Both of these issues should now be fixed, feel free to reopen if not.

**Comment by paveldoreuli** [comment]
Thank you for support! I'm reinstall new vtrsion? but still have same error(
I'm also attach one json file from channel #obchiy for test. there no sensetive information)
![Screenshot 2022-10-06 at 00 26 06](https://user-images.githubusercontent.com/114866573/194167623-95cd69b5-24b3-4305-858a-4b4b74005783.png)
[obchiy.zip](https://github.com/pR0Ps/slack-to-discord/files/9719121/obchiy.zip)
