### ISSUE TITLE
Unable to handle private channels out of the box

### ISSUE THREAD

**Issue by bguscott** [pR0Ps/slack-to-discord#5]
## Issue
For slack exports that contain private channels, the file `channels.json` does not contain a pre-populated list of channel information like it does for public channels. 

## Workaround
Manually creating an entry for each channel and updating `channels.json` appears to work. For example, using the following template to create additional entries in `channels.json` as needed:

```
[
{
    "id": "",		# Can be pulled from the URL when visiting the channel within the browser (e.g., "CENHP1B6P")
    "name": "",		# Channel name
    "created": ,	# Channel creation timestamp in epoch format
    "creator": "",	# Channel created user in obfuscated format (e.g., "UEMYJ1186")
    "is_archived": false,
    "is_general": false,
    "members": [
        "",		# Channel members in obfuscated format (e.g., "UEMYJ1186")
        ""		# Additional channel members as needed in obfuscated format (e.g., "UEMYJ1186")
    ],
    "topic": {
        "value": "",	# Channel topic 
        "creator": "",	# User in obfuscated format (e.g., "UEMYJ1186")
        "last_set":	# Epoch time
    },
    "purpose": {
        "value": "",	# Channel purpose 
        "creator": "",	# User in obfuscated format (e.g., "UEMYJ1186")
        "last_set":	# Epoch time
    }
}
]
```

**Comment by pR0Ps** [comment]
Would you be able to send me a small sample of a redacted private Slack export? Either attaching here or emailing me directly is fine. I'd like to make this program automatically import private channels as well, but I haven't been able to get Slack to give me a private export to test against so everything related to private channels and such is just a guess at this point.

**Comment by bguscott** [comment]
Guess I didn't look very hard, because that's exactly right :). 

Taking a look at my `groups.json` file it contains all my private channels, and only the private channels. Schema is also the same except for the `"is_general"` key.

Happy to test any changes against my private export - it has around 25,000 messages.

**Comment by bguscott** [comment]
[testing/private-export](https://github.com/pR0Ps/slack-to-discord/compare/testing/private-export) appears to be working. Looks like it can be merged and this issue closed.

**Comment by pR0Ps** [comment]
Should all be working as of the latest commit, thanks for testing it!
