### ISSUE TITLE
Problem with the Guild

### ISSUE THREAD

**Issue by antoniosantosramos** [pR0Ps/slack-to-discord#7]
Hello. I'm using the py script to do an export to Slack, but it gives me an error right at the last step

Exception: Guild 'number_of_mi_server' not accessible to the bot. Available guild(s): 'name_of_my_server'

The bot is registered in Discord before that process.
The problem is that I actually pass the server ID value to it, but it says it doesn't exist and returns the server name. But that name also corresponds to that ID.
![problem_slack_discord](https://user-images.githubusercontent.com/20588051/188517892-4b5a5de4-3b5f-4371-8393-caf9cfd100b5.jpg)

**Comment by pR0Ps** [comment]
The program is expecting to be given the guild name, not the guild ID. Passing the guild name instead of the ID on the CLI should work.

**Comment by antoniosantosramos** [comment]
Okay. Perfect. That works. 
But it is necessary that the name doesn't have spaces. That was my additional problem
You know that Discord allows spaces within the server name.
Thank you very much. It's a good script

**Comment by pR0Ps** [comment]
You can specify a guild name with spaces in it on the command line by enclosing it in quotes (ex: `slack-to-discord -g "your guild name here"`)
