### ISSUE TITLE
Is it possible to change the author of the message?

### ISSUE THREAD

**Issue by antoniosantosramos** [pR0Ps/slack-to-discord#8]
One limitation is that currently the authorship of the new message belongs to the bot.

![image](https://user-images.githubusercontent.com/20588051/191376711-03b95f95-47d2-4798-af74-924e62fa472c.png)

Can the author of the message be made to be the same as the original Slack message? And if so, do you plan to do it in an upcoming version?

I'm asking because as it's a third person message (a bot) I can't edit it on Discord even though I'm the person who wrote it on Slack.

I guess it's not possible to change the bot icon and replace it in Discord with the original author's icon, right?
Thanks in advance

**Comment by pR0Ps** [comment]
It does seem like there's a way to disguise the bot as a user with some [webhook hackery](https://stackoverflow.com/a/65894234/369977). Apparently the [NQN bot](https://nqn.blue/) uses this method. I'm not sure if this will allow you to edit the messages though since it seems like it's still the bot actually posting the message.

**Comment by pR0Ps** [comment]
@antoniosantosramos #10 changes the name and avatar of imported messages to match the Slack users (see that PR for a screenshot). Feel free to try out the version on that branch and let me know if you encounter issues.

This doesn't address your issue of editing the message, but I don't think that's possible.

**Comment by antoniosantosramos** [comment]
Wow!!
It is fantastic news. 
I have used the version from the master branch, but there is a problem in my execution due to the versions. Do you know what's the problem?

![image](https://user-images.githubusercontent.com/20588051/193432072-dbc2a63a-b0a6-41f0-9295-894e52ef9549.png)

I hace the last releases in several scripts/app...
![image](https://user-images.githubusercontent.com/20588051/193432088-c1f4f9a5-1693-4640-a998-40736e9aa18b.png)

**Comment by antoniosantosramos** [comment]
Wow!!
It is fantastic news. Thanks

I have used the version from the master branch. Use the real name in the messages, but I can't change the icon image.
In the example of your image, different icons appear depending on the user. How do you recognize that user?

![image](https://user-images.githubusercontent.com/20588051/193433270-2eacccec-4169-4439-a63f-b9987c0c03da.png)

In the image that appears, each message is written separately by the bot (and therefore could have a different profile image). But when I import my "export" Slack zip, several messages from different users appear under the same bot. 
Why are different?

![image](https://user-images.githubusercontent.com/20588051/193433734-61d35a95-9ac7-432b-a513-a9c91dbb1236.png)

**Comment by pR0Ps** [comment]
You were still using the old version which didn't change the names and icons (this was also why messages were all grouped under the same bot). The changes I made in #10 have now been merged to master so if you update and reinstall you should start seeing the new usernames and icons.
